const supported_currencies = [
    {abbreviation: "AED", description: "United Arab Emirates Dirham"},
    {abbreviation: "AFN", description: "Afghan Afghani"},
    {abbreviation: "ALL", description: "Albanian Lek"},
    {abbreviation: "AMD", description: "Armenian Dram"},
    {abbreviation: "ANG", description: "NL Antillean Guilder"},
    {abbreviation: "AOA", description: "Angolan Kwanza"},
    {abbreviation: "ARS", description: "Argentine Peso"},
    {abbreviation: "AUD", description: "Australian Dollar"},
    {abbreviation: "AWG", description: "Aruban Florin"},
    {abbreviation: "AZN", description: "Azerbaijani Manat"},
    {abbreviation: "BAM", description: "Bosnia-Herzegovina Convertible Mark"},
    {abbreviation: "BBD", description: "Barbadian Dollar"},
    {abbreviation: "BDT", description: "Bangladeshi Taka"},
    {abbreviation: "BGN", description: "Bulgarian Lev"},
    {abbreviation: "BHD", description: "Bahraini Dinar"},
    {abbreviation: "BIF", description: "Burundian Franc"},
    {abbreviation: "BMD", description: "Bermudan Dollar"},
    {abbreviation: "BND", description: "Brunei Dollar"},
    {abbreviation: "BOB", description: "Bolivian Boliviano"},
    {abbreviation: "BRL", description: "Brazilian Real"},
    {abbreviation: "BSD", description: "Bahamian Dollar"},
    {abbreviation: "BTN", description: "Bhutanese Ngultrum"},
    {abbreviation: "BWP", description: "Botswanan Pula"},
    {abbreviation: "BYN", description: "Belarusian Ruble"},
    {abbreviation: "BZD", description: "Belize Dollar"},
    {abbreviation: "BZD", description: "Belize Dollar"},
    {abbreviation: "CAD", description: "Canadian Dollar"},
    {abbreviation: "CDF", description: "Congolese Franc"},
    {abbreviation: "CHF", description: "Swiss Franc"},
    {abbreviation: "CLF", description: "Unidad de Fomento"},
    {abbreviation: "CLF", description: "Unidad de Fomento"},
    {abbreviation: "CLP", description: "Chilean Peso"},
    {abbreviation: "CNY", description: "Chinese Yuan"},
    {abbreviation: "COP", description: "Coombian Peso"},
    {abbreviation: "CRC", description: "Costa Rican Colón"},
    {abbreviation: "CUC", description: "Cuban Convertible Peso"},
    {abbreviation: "CUP", description: "Cuban Peso"},
    {abbreviation: "CVE", description: "Cape Verdean Escudo"},
    {abbreviation: "CZK", description: "Czech Republic Koruna"},
    {abbreviation: "DJF", description: "Djiboutian Franc"},
    {abbreviation: "DKK", description: "Danish Krone"},
    {abbreviation: "DOP", description: "Dominican Peso"},
    {abbreviation: "DZD", description: "Algerian Dinar"},
    {abbreviation: "EGP", description: "Egyptian Pound"},
    {abbreviation: "ERN", description: "Eritrean Nakfa"},
    {abbreviation: "ETB", description: "Ethiopian Birr"},
    {abbreviation: "EUR", description: "Euro"},
    {abbreviation: "FJD", description: "Fijian Dollar"},
    {abbreviation: "FKP", description: "Falkland Islands Pound"},
    {abbreviation: "GBP", description: "British Pound Sterling"},
    {abbreviation: "GEL", description: "Georgian Lari"},
    {abbreviation: "GGP", description: "Guernsey pound"},
    {abbreviation: "GHS", description: "Ghanaian Cedi"},
    {abbreviation: "GIP", description: "Gibraltar Pound"},
    {abbreviation: "GMD", description: "Gambian Dalasi"},
    {abbreviation: "GNF", description: "Guinean Franc"},
    {abbreviation: "GTQ", description: "Guatemalan Quetzal"},
    {abbreviation: "GYD", description: "Guyanaese Dollar"},
    {abbreviation: "HKD", description: "Hong Kong Dollar"},
    {abbreviation: "HNL", description: "Honduran Lempira"},
    {abbreviation: "HRK", description: "Croatian Kuna"},
    {abbreviation: "HTG", description: "Haitian Gourde"},
    {abbreviation: "HUF", description: "Hungarian Forint"},
    {abbreviation: "IDR", description: "Indonesian Rupiah"},
    {abbreviation: "ILS", description: "Israeli New Sheqel"},
    {abbreviation: "IMP", description: "Manx pound"},
    {abbreviation: "INR", description: "Indian Rupee"},
    {abbreviation: "IQD", description: "Iraqi Dinar"},
    {abbreviation: "IRR", description: "Iranian Rial"},
    {abbreviation: "ISK", description: "Icelandic Króna"},
    {abbreviation: "JEP", description: "Jersey pound"},
    {abbreviation: "JMD", description: "Jamaican Dollar"},
    {abbreviation: "JOD", description: "Jordanian Dinar"},
    {abbreviation: "JPY", description: "Japanese Yen"},
    {abbreviation: "KES", description: "Kenyan Shilling"},
    {abbreviation: "KGS", description: "Kyrgystani Som"},
    {abbreviation: "KHR", description: "Cambodian Riel"},
    {abbreviation: "KMF", description: "Comorian Franc"},
    {abbreviation: "KPW", description: "North Korean Won"},
    {abbreviation: "KRW", description: "South Korean Won"},
    {abbreviation: "KWD", description: "Kuwaiti Dinar"},
    {abbreviation: "KYD", description: "Cayman Islands Dollar"},
    {abbreviation: "KZT", description: "Kazakhstani Tenge"},
    {abbreviation: "LAK", description: "Laotian Kip"},
    {abbreviation: "LBP", description: "Lebanese Pound"},
    {abbreviation: "LKR", description: "Sri Lankan Rupee"},
    {abbreviation: "LRD", description: "Liberian Dollar"},
    {abbreviation: "LSL", description: "Lesotho Loti"},
    {abbreviation: "LTL", description: "Lithuanian Litas"},
    {abbreviation: "LVL", description: "Latvian Lats"},
    {abbreviation: "LYD", description: "Libyan Dinar"},
    {abbreviation: "MAD", description: "Moroccan Dirham"},
    {abbreviation: "MDL", description: "Moldovan Leu"},
    {abbreviation: "MGA", description: "Malagasy Ariary"},
    {abbreviation: "MKD", description: "Macedonian Denar"},
    {abbreviation: "MMK", description: "Myanma Kyat"},
    {abbreviation: "MNT", description: "Mongolian Tugrik"},
    {abbreviation: "MOP", description: "Macanese Pataca"},
    {abbreviation: "MRO", description: "Mauritanian ouguiya"},
    {abbreviation: "MUR", description: "Mauritian Rupee"},
    {abbreviation: "MVR", description: "Maldivian Rufiyaa"},
    {abbreviation: "MWK", description: "Malawian Kwacha"},
    {abbreviation: "MXN", description: "Mexican Peso"},
    {abbreviation: "MYR", description: "Malaysian Ringgit"},
    {abbreviation: "MZN", description: "Mozambican Metical"},
    {abbreviation: "NAD", description: "Namibian Dollar"},
    {abbreviation: "NGN", description: "Nigerian Naira"},
    {abbreviation: "NIO", description: "Nicaraguan Córdoba"},
    {abbreviation: "NOK", description: "Norwegian Krone"},
    {abbreviation: "NPR", description: "Nepalese Rupee"},
    {abbreviation: "NZD", description: "New Zealand Dollar"},
    {abbreviation: "OMR", description: "Omani Rial"},
    {abbreviation: "PAB", description: "Panamanian Balboa"},
    {abbreviation: "PEN", description: "Peruvian Nuevo Sol"},
    {abbreviation: "PGK", description: "Papua New Guinean Kina"},
    {abbreviation: "PHP", description: "Philippine Peso"},
    {abbreviation: "PKR", description: "Pakistani Rupee"},
    {abbreviation: "PLN", description: "Polish Zloty"},
    {abbreviation: "PYG", description: "Paraguayan Guarani"},
    {abbreviation: "QAR", description: "Qatari Rial"},
    {abbreviation: "RON", description: "Romanian Leu"},
    {abbreviation: "RSD", description: "Serbian Dinar"},
    {abbreviation: "RUB", description: "Russian Ruble"},
    {abbreviation: "RWF", description: "Rwandan Franc"},
    {abbreviation: "SAR", description: "Saudi Riyal"},
    {abbreviation: "SBD", description: "Solomon Islands Dollar"},
    {abbreviation: "SCR", description: "Seychellois Rupee"},
    {abbreviation: "SDG", description: "Sudanese Pound"},
    {abbreviation: "SEK", description: "Swedish Krona"},
    {abbreviation: "SGD", description: "Singapore Dollar"},
    {abbreviation: "SHP", description: "Saint Helena Pound"},
    {abbreviation: "SLL", description: "Sierra Leonean Leone"},
    {abbreviation: "SOS", description: "Somali Shilling"},
    {abbreviation: "SRD", description: "Surinamese Dollar"},
    {abbreviation: "STD", description: "São Tomé and Príncipe dobra"},
    {abbreviation: "SVC", description: "Salvadoran Colón"},
    {abbreviation: "SYP", description: "Syrian Pound"},
    {abbreviation: "SZL", description: "Swazi Lilangeni"},
    {abbreviation: "THB", description: "Thai Baht"},
    {abbreviation: "TJS", description: "Tajikistani Somoni"},
    {abbreviation: "TMT", description: "Turkmenistani Manat"},
    {abbreviation: "TND", description: "Tunisian Dinar"},
    {abbreviation: "TOP", description: "Tongan Paʻanga"},
    {abbreviation: "TRY", description: "Turkish Lira"},
    {abbreviation: "TTD", description: "Trinidad and Tobago Dollar"},
    {abbreviation: "TWD", description: "New Taiwan Dollar"},
    {abbreviation: "TZS", description: "Tanzanian Shilling"},
    {abbreviation: "UAH", description: "Ukrainian Hryvnia"},
    {abbreviation: "UGX", description: "Ugandan Shilling"},
    {abbreviation: "USD", description: "US Dollar"},
    {abbreviation: "UYU", description: "Uruguayan Peso"},
    {abbreviation: "UZS", description: "Uzbekistan Som"},
    {abbreviation: "VEF", description: "Venezuelan Bolívar"},
    {abbreviation: "VND", description: "Vietnamese Dong"},
    {abbreviation: "VUV", description: "Vanuatu Vatu"},
    {abbreviation: "WST", description: "Samoan Tala"},
    {abbreviation: "XAF", description: "CFA Franc BEAC"},
    {abbreviation: "XAG", description: "Silver Ounce"},
    {abbreviation: "XAU", description: "Gold Ounce"},
    {abbreviation: "XCD", description: "East Caribbean Dollar"},
    {abbreviation: "XDR", description: "Special drawing rights"},
    {abbreviation: "XOF", description: "CFA Franc BCEAO"},
    {abbreviation: "XPF", description: "CFP Franc"},
    {abbreviation: "YER", description: "Yemeni Rial"},
    {abbreviation: "ZAR", description: "South African Rand"},
    {abbreviation: "ZMK", description: "Zambian Kwacha"},
    {abbreviation: "ZMW", description: "Zambian Kwacha"},
    {abbreviation: "ZWL", description: "Zimbabwean dollar"},
    {abbreviation: "XPT", description: "Platinum Ounce"},
    {abbreviation: "XPD", description: "Palladium Ounce"},
    {abbreviation: "BTC", description: "Bitcoin"},
    {abbreviation: "ETH", description: "Ethereum"},
    {abbreviation: "BNB", description: "Binance"},
    {abbreviation: "XRP", description: "Ripple"},
    {abbreviation: "SOL", description: "Solana"},
    {abbreviation: "DOT", description: "Polkadot"},
    {abbreviation: "ADA", description: "Cardano"}
];

const isSupportedCurrency = (target) => {
    for ( let i = 0; i < supported_currencies.length; i++ ) {
        if ( supported_currencies[i].abbreviation === target ) {
            return true;
        }
    }
    return false;
}

export {
    isSupportedCurrency
};